services:
  minio:
    image: minio/minio:latest
    container_name: atlas-minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atlas-network

  minio-init:
    image: minio/mc:latest
    container_name: atlas-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/atlas-files --ignore-existing;
      mc anonymous set download myminio/atlas-files;
      echo 'MinIO initialization complete';
      "
    networks:
      - atlas-network

  atlas-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_NAME: "Chat UI"
    container_name: atlas-ui-3
    ports:
      - "8000:8000"
    environment:
      - DEBUG_MODE=true
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET_NAME=atlas-files
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_REGION=us-east-1
      - S3_USE_SSL=false
      - APP_LOG_DIR=/app/logs
    volumes:
      - ./logs:/app/logs
      - ./config/overrides:/app/config/overrides
    depends_on:
      minio:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    networks:
      - atlas-network

networks:
  atlas-network:
    driver: bridge

volumes:
  minio-data:
